application: lanternctrlpy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
    - url: /cron
      script: app.app
      login: admin
    - url: /.*
      script: app.app

inbound_services:
    - xmpp_presence

libraries:
    - name: ssl
      version: "2.7"


